let dados = [
    {
        nome: "Falcon 9",
        pais: "Estados Unidos",
        agencia: "SpaceX",
        tipo: "orbital",
        cargaUtil: "Starlink",
        dataLancamento: "27 de abril de 2023",
        baseLancamento: "Cabo Canaveral",
        status: "Sucesso",
        imagem: "falcon91.jpg",
        tags: "2023 eua usa spacex starlink",
        link: "https://www.spacex.com/launches/mission/?missionId=sl3-5-pl"
    },
    {
        nome: "Artemis I",
        pais: "Estados Unidos",
        agencia: "NASA",
        tipo: "orbital",
        cargaUtil: "Orion",
        dataLancamento: "16 de novembro de 2022",
        baseLancamento: "Kennedy Space Center",
        status: "Sucesso",
        imagem: "artemis1.jpg",
        tags: "2022 eua usa nasa lua",
        link: "https://www.nasa.gov/artemis"
      },
      {
        nome: "Soyuz MS-23",
        pais: "Rússia",
        agencia: "Roscosmos",
        tipo: "orbital",
        cargaUtil: "Tripulação",
        dataLancamento: "20 de fevereiro de 2023",
        baseLancamento: "Cosmódromo de Baikonur",
        status: "Sucesso",
        imagem: "SoyuzMS-23.jpg",
        tags: "2023 russia iss",
        link: "https://www.roscosmos.ru/21855/"
      },
      {
        nome: "Chandrayaan-3",
        pais: "Índia",
        agencia: "ISRO",
        tipo: "lunar",
        cargaUtil: "Lander e Rover",
        dataLancamento: "14 de julho de 2023",
        baseLancamento: "Satish Dhawan Space Centre",
        status: "Sucesso",
        imagem: "Chandrayaan-3.jpg",
        tags: "2023 india lua",
        link: "https://www.isro.gov.in/"
      },
      {
        nome: "Shenzhou 16",
        pais: "China",
        agencia: "CMSA",
        tipo: "orbital",
        cargaUtil: "Tripulação",
        dataLancamento: "30 de maio de 2023",
        baseLancamento: "Jiuquan Satellite Launch Center",
        status: "Sucesso",
        imagem: "Shenzhou 16.jpg",
        tags: "2023 china estação espacial chinesa",
        link: "https://www.cmsa.gov.cn/"
      },
      {
        nome: "Space Shuttle STS-31",
        pais: "Estados Unidos",
        agencia: "NASA",
        tipo: "orbital",
        cargaUtil: "Telescópio Hubble",
        dataLancamento: "24 de abril de 1990",
        baseLancamento: "Kennedy Space Center",
        status: "Sucesso",
        imagem: "shuttle.jpg",
        tags: "1990 eua hubble nasa",
        link: "https://hubblesite.org/"
    },
    {
        nome: "Apollo 11",
        pais: "Estados Unidos",
        agencia: "NASA",
        tipo: "lunar",
        cargaUtil: "Módulo Lunar",
        dataLancamento: "16 de julho de 1969",
        baseLancamento: "Kennedy Space Center",
        status: "Sucesso",
        imagem: "Apollo 11.jpg",
        tags: "1969 eua nasa lua apolo lunar",
        link: "https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html"
    },
    {
        nome: "Vostok 1",
        pais: "União Soviética",
        agencia: "Soviet Space Program",
        tipo: "orbital",
        cargaUtil: "Tripulação (Yuri Gagarin)",
        dataLancamento: "12 de abril de 1961",
        baseLancamento: "Cosmódromo de Baikonur",
        status: "Sucesso",
        imagem: "Vostok 1.jpg",
        tags: "1961 urss rússia gagarin",
        link: "https://www.roscosmos.ru/"
    },
    {
        nome: "Atlas V",
        pais: "Estados Unidos",
        agencia: "NASA",
        tipo: "planetário",
        cargaUtil: "Rover Perseverance",
        dataLancamento: "30 de julho de 2020",
        baseLancamento: "Cabo Canaveral",
        status: "Sucesso",
        imagem: "Atlas V.jpg",
        tags: "2020 eua marte nasa rover mars perseverance",
        link: "https://mars.nasa.gov/mars2020/"
    },
    {
        nome: "BepiColombo",
        pais: "Agência Espacial Europeia",
        agencia: "ESA",
        tipo: "planetário",
        cargaUtil: "Sonda Espacial",
        dataLancamento: "20 de outubro de 2018",
        baseLancamento: "Centro Espacial de Kourou",
        status: "Sucesso",
        imagem: "BepiColombo.jpg",
        tags: "2018 europa mercúrio",
        link: "https://sci.esa.int/web/bepicolombo"
    },
    {
        nome: "Galileo IOV-1",
        pais: "Agência Espacial Europeia",
        agencia: "ESA",
        tipo: "orbital",
        cargaUtil: "Satélites de navegação",
        dataLancamento: "21 de outubro de 2011",
        baseLancamento: "Centro Espacial de Kourou",
        status: "Sucesso",
        imagem: "Galileo IOV-1.jpg",
        tags: "2011 europa navegação gps",
        link: "https://www.esa.int/Applications/Navigation/Galileo"
    },
    {
        nome: "Hayabusa 2",
        pais: "Japão",
        agencia: "JAXA",
        tipo: "planetário",
        cargaUtil: "Sonda",
        dataLancamento: "3 de dezembro de 2014",
        baseLancamento: "Tanegashima Space Center",
        status: "Sucesso",
        imagem: "Hayabusa 2.jpg",
        tags: "2014 japão asteroide",
        link: "https://www.hayabusa2.jaxa.jp/en/"
    }
];